# String is express in three way 

    # 1. Single Quotes: 'single_quote'
    # 2. Double Quotes: "double_quote"
    # 3. Triple Quotes: ''' triple_quote ''' or """ triple_quote """

# 1st problem of single quote (when we use single quote in string)
# single_quote = 'There are many people's'    # -> this is generated by error

# solution by double quotation and triple quote
# for double quote

double_quote = "There is many people's' "
print(double_quote)

# 2nd problem of double quote when we use double quote in string
# double_quote = "There is many "people"s"    # -> this is generated by error
# solution by single and triple quotes

single_quote = 'There is many "people"s'
print(single_quote)

# similar to triple quote