""" 
Topic : set.remove(element)
 obj : remove the element from set

 syntax: 
     set_name.remove(element)
"""
# eg_01: create a set(remember that set is unordered)
set_1 = {"Kz", 4039, "CSE", 98.54, "Dhaka", 99.9}
print("Set_01: ", set_1)
print("length: ", len(set_1))

# Remove an element form set_1
set_1.remove(99.9)

print("\nAfter removing 99.9: ", set_1)
print("length: ",len(set_1))

# add an element
set_1.add("EEE")
print("\nAfter adding EEE: ", set_1)
print("length: ",len(set_1))

# remove an element
set_1.remove("EEE")
print("\nAfter remove EEE : ", set_1)

# remove an element which is not in set that is generated by error
set_1.remove(123)
print("\nAfter trying to remove 123: ", set_1)

# similar to when we can access an element which is not in set
# that is generated by error


